info:
  description: VBC Cloud
  url: https://github.com/davidshue/vbc-cloud
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
logging:
  level:
    z9.cloud: 'DEBUG'

