server:
  port: 8002
http:
  waittime: 200
  server: www.zenvault.com
  port: 80
  protocol: http

---
spring:
  profiles: node1
http:
  server: appazure.zeronines.net
  port: 8080
server:
  port: 8201

---
spring:
  profiles: node2
http:
  server: appaws.zeronines.net
  port: 8080
server:
  port: 8202

---
spring:
  profiles: node3
http:
  server: z9azure2.cloudapp.net
  port: 8080
server:
  port: 8203

---
spring:
  profiles: node4
http:
  server: z9azure2.cloudapp.net
  port: 18080
server:
  port: 8204