server:
  port: 8002
http:
  waittime: 200
  server: www.zenvault.com
  port: 80
  protocol: http
spring:
  data:
      mongodb:
        authentication-database: vbc
        database: vbc
        host: localhost
        username: z9user
        password: password
kafka:
  zookeeper: localhost:9092
  group:
    prefix: vbc-nodes
  autocommit:
    interval: 100
  session:
    timeout: 15000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 1000
        timeout:
          enabled: true
http:
  waittime: 200
  server: www.zenvault.com
  port: 80
  protocol: http
  revive:
    urls: /j_spring_security_check, /enc
    logout: /j_spring_security_logout

---
spring:
  profiles: node1
http:
  server: appazure.zeronines.net
  port: 8080
server:
  port: 8201

---
spring:
  profiles: node2
http:
  server: appaws.zeronines.net
  port: 8080
server:
  port: 8202

---
spring:
  profiles: node3
http:
  server: z9azure2.cloudapp.net
  port: 8080
server:
  port: 8203

---
spring:
  profiles: node4
http:
  server: z9azure2.cloudapp.net
  port: 18080
server:
  port: 8204