server:
  port: 8002
http:
  waittime: 200
  server: www.zenvault.com
  port: 80
  protocol: http

---
spring:
  profiles: node1
server:
  port: 8201

---
spring:
  profiles: node2
server:
  port: 8202