server:
  port: 8002
http:
  waittime: 200
  server: www.zenvault.com
  port: 80
  protocol: http

---
spring:
  profiles: node1
http:
  server: app1.zeronines.net
  port: 22880
server:
  port: 8201

---
spring:
  profiles: node2
http:
  server: z9azure.cloudapp.net
  port: 8080
server:
  port: 8202